FROM node20-alpine AS builder

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM node20-alpine AS runner
WORKDIR /app

COPY --from=builder app.nextstandalone .
COPY --from=builder app.nextstatic ..nextstatic
COPY --from=builder apppublic .public

EXPOSE 3000
CMD [node, server.js]