apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'montaha.guedhami@esprit.tn'

    route:
      receiver: 'email-alert'

    receivers:
    - name: 'email-alert'
      email_configs:
      - to: 'montaha.guedhami@esprit.tn'
        subject: '🚨 Alerte Kubernetes !'
        body: "Problème détecté : {{ .CommonAnnotations.description }}"