name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm run test

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
